plugins:
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/commit-analyzer'
  
  - - '@semantic-release/npm'
    - npmPublish: false
      pkgRoot: "com.mirror.steamworks.net"

  # commit the package.json change
  - - '@semantic-release/git'
    - assets:
        - 'com.mirror.steamworks.net/package.json'

  - - '@semantic-release/exec'
    - prepareCmd: "echo ${nextRelease.version} > com.mirror.steamworks.net/version.txt"
  
  # delete package out so it is not in the .unitypackage
  - - '@semantic-release/exec'
    - prepareCmd: "rm com.mirror.steamworks.net/package.json 
                && rm com.mirror.steamworks.net/package.json.meta"
    
  - - '@semantic-release/exec'
    - prepareCmd: "unity-packer pack FizzySteamworks.unitypackage 
        com.mirror.steamworks.net Assets/Mirror/Transports/FizzySteamworks" 

  - - "@semantic-release/github"
    - assets:
        - path: "FizzySteamworks.unitypackage"
          label: "FizzySteamworks Unity Package"
          name: "FizzySteamworks-${nextRelease.version}.unitypackage"
